includes("lib/commonlibsse-ng")
set_project("EquipmentColorRuntime")
set_version("0.2.2")
set_languages("c++23")
set_arch("x64")
set_encodings("utf-8")
add_rules("mode.debug", "mode.releasedbg")

target("RuntimeMinHook")
    set_kind("static")
    set_runtimes("MD")
    add_files("vendor/minhook/src/buffer.c", "vendor/minhook/src/hook.c", "vendor/minhook/src/trampoline.c", "vendor/minhook/src/hde/hde64.c")
    add_includedirs("vendor/minhook/include", {public = true})

target("RuntimeDrawHooks")
    set_kind("static")
    set_runtimes("MD")
    add_deps("RuntimeMinHook", "RuntimeShaderCore")
    add_files("src/DrawInterception.cpp")
    add_includedirs("src", {public = true})
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX")

target("RuntimeShaderCore")
    set_kind("static")
    set_runtimes("MD")
    add_files("src/ShaderPatch.cpp", "src/D3DSlots.cpp", "vendor/dxbc-hash/DxbcHash.cpp")
    add_includedirs("src", {public = true})
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX")

target("EquipmentColorRuntime")
    add_rules("commonlibsse-ng.plugin", {
        name = "EquipmentColorRuntime", author = "Equipment Color Runtime contributors",
        description = "Per-equipment diffuse shader recoloring without generated textures."
    })
    add_deps("RuntimeShaderCore", "RuntimeDrawHooks")
    add_files("src/Plugin.cpp", "src/Equipment.cpp", "src/Menu.cpp", "src/RuntimeRenderer.cpp")
    add_includedirs("src", "vendor/menu-example/include")
    add_syslinks("d3d11")
    set_pcxxheader("src/PCH.h")

target("RuntimeShaderTests")
    set_kind("binary")
    set_default(false)
    set_runtimes("MD")
    add_deps("RuntimeShaderCore")
    add_files("tests/RuntimeShaderTests.cpp")
    add_includedirs("src")
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX")
    add_syslinks("d3d11", "d3dcompiler")

target("RuntimeHookTests")
    set_kind("binary")
    set_default(false)
    set_runtimes("MD")
    add_deps("RuntimeShaderCore", "RuntimeDrawHooks", "commonlibsse-ng")
    add_files("tests/RuntimeShaderTests.cpp", "src/RuntimeRenderer.cpp")
    add_includedirs("src")
    add_defines("ER_RENDER_TEST", "WIN32_LEAN_AND_MEAN", "NOMINMAX")
    set_pcxxheader("src/PCH.h")
    add_syslinks("d3d11", "d3dcompiler")
